name: Kitsune
favicon: null
layout_spectrum: 0.7973588709719479
typography_spectrum: 0.007695212960243225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7495470596477389
  lightness: 0.3874224463943392
  saturation: 0.5466014517005533
  rhythmicContrast: 0.13606477831490338
purpose: []
