name: Kitsune
favicon: null
layout_spectrum: 0.69286
typography_spectrum: 0.35639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5bf9a'
    - '#1f3c40'
    - '#010101'
    - '#bc6601'
  brandStrength: 0.979729
  lightness: 0.708333
  saturation: 0.546601
  rhythmicContrast: 0.66554
purpose: []
