name: Kitsune
favicon: null
layout_spectrum: 0.69286
typography_spectrum: 0.35639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#daab67'
    - '#000000'
    - '#22ace4'
    - '#e81123'
  brandStrength: 0.8125
  lightness: 0.3874224463943392
  saturation: 0.5466014517005533
  rhythmicContrast: 0.5
purpose: []
