analytics: {}
color:
  brandColors:
    - '#D8B0B0'
    - '#500008'
    - '#986870'
    - '#B04800'
    - '#D09898'
  brandStrength: 0.979729
  lightness: 0.708333
  rhythmicContrast: 0.66554
  saturation: 0.546601
cta: {}
layout_spectrum: 0.69286
name: Kitsune
opengraph: {}
purpose: []
typography_spectrum: 0.35639
